### PR TITLE
#159232286 Setup unit test

### PR DESCRIPTION
**Pull request by Oloyedesinmiloluwa**
#### What does this PR do?
Setup unit test
#### Description of Task to be completed?
- add mocha, chai and chai-http dependencies
- add test script in package.json
- add test entry point: index.test.js
#### How should this be manually tested?
- Check the build status on Travis
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/159232286

### CODE REVIEW

**Comment by anuonifade** [comment]
@Oloyedesinmiloluwa I expect that we are testing for controller, model and API endpoints. We should have folders for the different tests categories and `index.test.js` runs everything.

**Comment by Oloyedesinmiloluwa** [comment]
Thanks for your review @andela-aonifade I have incorporated the changes

**Comment by anuonifade** [comment]
@Oloyedesinmiloluwa I am not sure this is the best way to go about the task.

**Comment by Oloyedesinmiloluwa** [comment]
Alright, my intention for using this method was to make the test reusable however, I will use another method possibly it can be a better choice, or do you have a recommendation?

**Comment by Oloyedesinmiloluwa** [comment]
I will push an improvement to it soon, I am on it, thanks

**Comment by anuonifade** [comment]
@Oloyedesinmiloluwa since all your test are all in a single folder `test`. You can run your mocha to run all test files in the test folder. Note that each test i.e. Controller, Model, and API tests are expected to run independently.

**Comment by Oloyedesinmiloluwa** [comment]
Alright @andela-aonifade I have made mocha to run all test files in the test folder , thanks

**Pull request merged**
